parameters:
    locale: 'en'

services:

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    MyBudget\Application\Command\:
        resource: '../src/Application/Command'

    MyBudget\Application\Controller\:
        resource: '../src/Application/Controller'
        tags: ['controller.service_arguments']

    MyBudget\Domain\Repository\BudgetRepository:
        class: MyBudget\Infrastructure\Repository\BudgetRepository
